// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: esp32_ssd1306_128x64_test

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void chartZoom_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Welcome_Screen
void ui_Welcome_Screen_screen_init(void);
void ui_event_Welcome_Screen(lv_event_t * e);
lv_obj_t * ui_Welcome_Screen;
lv_obj_t * ui_lblWelcome;

// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
void ui_event_Loading_Screen(lv_event_t * e);
lv_obj_t * ui_Loading_Screen;
lv_obj_t * ui_lblLoading;
lv_obj_t * ui_spinnerLoading;

// SCREEN: ui_Roller_Screen
void ui_Roller_Screen_screen_init(void);
void ui_event_Roller_Screen(lv_event_t * e);
lv_obj_t * ui_Roller_Screen;
lv_obj_t * ui_rollerMenu;

// SCREEN: ui_Switch_Screen
void ui_Switch_Screen_screen_init(void);
void ui_event_Switch_Screen(lv_event_t * e);
lv_obj_t * ui_Switch_Screen;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Switch3;

// SCREEN: ui_Chart_Screen
void ui_Chart_Screen_screen_init(void);
void ui_event_Chart_Screen(lv_event_t * e);
lv_obj_t * ui_Chart_Screen;
lv_obj_t * ui_chartOne;

// SCREEN: ui_Final_Screen
void ui_Final_Screen_screen_init(void);
void ui_event_Final_Screen(lv_event_t * e);
lv_obj_t * ui_Final_Screen;
lv_obj_t * ui_btnRestart;
lv_obj_t * ui_Label5;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 1
    #error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void chartZoom_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_width);
    lv_anim_set_values(&PropertyAnimation_0, 0, 128);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);
    ui_anim_user_data_t * PropertyAnimation_1_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_1_user_data->target = TargetObject;
    PropertyAnimation_1_user_data->val = -1;
    lv_anim_t PropertyAnimation_1;
    lv_anim_init(&PropertyAnimation_1);
    lv_anim_set_time(&PropertyAnimation_1, 1000);
    lv_anim_set_user_data(&PropertyAnimation_1, PropertyAnimation_1_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_1, _ui_anim_callback_set_height);
    lv_anim_set_values(&PropertyAnimation_1, 0, 64);
    lv_anim_set_path_cb(&PropertyAnimation_1, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_1, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_1, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_1, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_1, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_1, 0);
    lv_anim_set_early_apply(&PropertyAnimation_1, false);
    lv_anim_start(&PropertyAnimation_1);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Welcome_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_Loading_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 1500);
    }
}
void ui_event_Loading_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_Roller_Screen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 1500);
    }
}
void ui_event_Roller_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_roller_set_property(ui_rollerMenu, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 1);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_Switch_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 2000);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        _ui_roller_set_property(ui_rollerMenu, _UI_ROLLER_PROPERTY_SELECTED, 0);
    }
}
void ui_event_Switch_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_state_modify(ui_Switch2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
        _ui_screen_change(ui_Chart_Screen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 2000);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        _ui_state_modify(ui_Switch2, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}
void ui_event_Chart_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        chartZoom_Animation(ui_chartOne, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_Final_Screen, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 1600);
    }
}
void ui_event_Final_Screen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(ui_Welcome_Screen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 300);
        _ui_state_modify(ui_btnRestart, LV_STATE_PRESSED, _UI_MODIFY_STATE_TOGGLE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_mono_init(dispp, false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Welcome_Screen_screen_init();
    ui_Loading_Screen_screen_init();
    ui_Roller_Screen_screen_init();
    ui_Switch_Screen_screen_init();
    ui_Chart_Screen_screen_init();
    ui_Final_Screen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Welcome_Screen);
}
