// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: esp32_ssd1306_128x64_test

#ifndef _ESP32_SSD1306_128X64_TEST_UI_H
#define _ESP32_SSD1306_128X64_TEST_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void chartZoom_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Welcome_Screen
void ui_Welcome_Screen_screen_init(void);
void ui_event_Welcome_Screen(lv_event_t * e);
extern lv_obj_t * ui_Welcome_Screen;
extern lv_obj_t * ui_lblWelcome;
// SCREEN: ui_Loading_Screen
void ui_Loading_Screen_screen_init(void);
void ui_event_Loading_Screen(lv_event_t * e);
extern lv_obj_t * ui_Loading_Screen;
extern lv_obj_t * ui_lblLoading;
extern lv_obj_t * ui_spinnerLoading;
// SCREEN: ui_Roller_Screen
void ui_Roller_Screen_screen_init(void);
void ui_event_Roller_Screen(lv_event_t * e);
extern lv_obj_t * ui_Roller_Screen;
extern lv_obj_t * ui_rollerMenu;
// SCREEN: ui_Switch_Screen
void ui_Switch_Screen_screen_init(void);
void ui_event_Switch_Screen(lv_event_t * e);
extern lv_obj_t * ui_Switch_Screen;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Switch3;
// SCREEN: ui_Chart_Screen
void ui_Chart_Screen_screen_init(void);
void ui_event_Chart_Screen(lv_event_t * e);
extern lv_obj_t * ui_Chart_Screen;
extern lv_obj_t * ui_chartOne;
// SCREEN: ui_Final_Screen
void ui_Final_Screen_screen_init(void);
void ui_event_Final_Screen(lv_event_t * e);
extern lv_obj_t * ui_Final_Screen;
extern lv_obj_t * ui_btnRestart;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_MontserratSemiBold14);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
