// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: esp32_ssd1306_128x64_test

#include "ui.h"

void screen_loaded_func(lv_event_t * e)
{
	// Your code here
}
