// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: esp32_ssd1306_128x64_test

#include "../ui.h"

void ui_Roller_Screen_screen_init(void)
{
    ui_Roller_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Roller_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_rollerMenu = lv_roller_create(ui_Roller_Screen);
    lv_roller_set_options(ui_rollerMenu, "Option 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerMenu, 128);
    lv_obj_set_height(ui_rollerMenu, 64);
    lv_obj_set_align(ui_rollerMenu, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_rollerMenu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMenu, &ui_font_MontserratSemiBold14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rollerMenu, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMenu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMenu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_rollerMenu, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMenu, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMenu, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMenu, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Roller_Screen, ui_event_Roller_Screen, LV_EVENT_ALL, NULL);

}
