// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: esp32_ssd1306_128x64_test

#include "../ui.h"

void ui_Welcome_Screen_screen_init(void)
{
    ui_Welcome_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Welcome_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblWelcome = lv_label_create(ui_Welcome_Screen);
    lv_obj_set_width(ui_lblWelcome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblWelcome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblWelcome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblWelcome, "Welcome");
    lv_obj_set_style_text_font(ui_lblWelcome, &ui_font_MontserratSemiBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Welcome_Screen, ui_event_Welcome_Screen, LV_EVENT_ALL, NULL);

}
